export default [
  'QuestionCircleTwoTone',
  'PlusCircleTwoTone',
  'PauseCircleTwoTone',
  'MinusCircleTwoTone',
  'PlusSquareTwoTone',
  'MinusSquareTwoTone',
  'InfoCircleTwoTone',
  'ExclamationCircleTwoTone',
  'CloseCircleTwoTone',
  'CloseSquareTwoTone',
  'CheckCircleTwoTone',
  'CheckSquareTwoTone',
  'ClockCircleTwoTone',
  'WarningTwoTone',
  'StopTwoTone',
];
